# Generated by Django 4.2.7 on 2025-01-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionofficer',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='electionofficer',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
